### PR TITLE
Release v0.5

### PR DESCRIPTION
**Pull request by ilopezgp**
## Checklist before requesting a review / merging
- [x] I have formatted the code using `julia --project=.dev .dev/climaformat.jl .`
- [x] I have updated all test manifests using `julia --project .dev/up_deps.jl .` with Julia 1.7.3.
- [x] If core features are added, I have added appropriate test coverage.
- [x] If new functions and structs are added, they are documented through docstrings.

### CODE REVIEW

**Comment by ilopezgp** [comment]
@haakon-e could you see if you understand why the grid_search test is failing? Thanks.

**Comment by haakon-e** [comment]
> @haakon-e could you see if you understand why the grid_search test is failing? Thanks.

I think I found it. Can I push to this PR?

**Comment by haakon-e** [comment]
Fixed issue here and reported underlying bug to https://github.com/JuliaPlots/Makie.jl/issues/2070

**Pull request merged**
