### PR TITLE
Lazily download artifacts

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR makes the artifacts actually download lazily. See [this comment](https://github.com/CliMA/TurbulenceConvection.jl/pull/876#issue-1160517643).

### CODE REVIEW

**Comment by ilopezgp** [comment]
Oh, you are right, I didn't see the include there. I am fine with that if you prefer it. 

Should we move the lazy_downloads test command to another build kite task? It seems to be affecting SCT1_Benchmark, which does not use any artifacts. The error we see there is the one you mentioned in the comment linked above,

`ERROR: LoadError: HTTP/2 200 (Operation too slow. Less than 1 bytes/sec transferred the last 20 seconds) while requesting https://caltech.box.com/shared/static/0hnf7nkttueraaqf9tpkqsx38gjqx41p.nc`

**Comment by charleskawczynski** [comment]
Weird, I'll take a look

**Review by ilopezgp — APPROVED** [review]

**Comment by charleskawczynski** [comment]
I'm not sure this is any different, but we can monitor things if we see the errors pop up again.

**Comment by ilopezgp** [comment]
> I'm not sure this is any different, but we can monitor things if we see the errors pop up again.

Actually, I saw that error as well in PR #257. Weird.

**Pull request merged**
