### PR TITLE
Pin TC version

### PR DESCRIPTION
**Pull request by costachris**
## Checklist before requesting a review / merging
- [x] I have formatted the code using `julia --project=.dev .dev/climaformat.jl .`
- [x] I have updated all test manifests using `julia --project .dev/up_deps.jl .` with Julia 1.8.1.
- [x] If core features are added, I have added appropriate test coverage.
- [x] If new functions and structs are added, they are documented through docstrings.

### CODE REVIEW

**Comment by ilopezgp** [comment]
Ubuntu keeps failing... strange.

**Comment by costachris** [comment]
I'm also still getting AW method errors when running calibrations after pinning TC to 1.3.0. Looking into why...

**Comment by ilopezgp** [comment]
@costachris since the main branch is not working, you can merge this disabling the ubuntu CI flag on bors. We can fix it later.

**Comment by ilopezgp** [comment]
Deprecated by merge of #468

**Pull request closed without merging**
