### PR TITLE
update to CloudMicrophysics v0.8.0

### PR DESCRIPTION
**Pull request by trontrytel**

### CODE REVIEW

**Comment by trontrytel** [comment]
Does it mean we have to add a ClearDepot job for CalibrateEDMF?

**Comment by ilopezgp** [comment]
> Does it mean we have to add a ClearDepot job for CalibrateEDMF?

We have one, I will clear the depot

**Comment by trontrytel** [comment]
> > Does it mean we have to add a ClearDepot job for CalibrateEDMF?
> 
> We have one, I will clear the depot

Thanks, I looked for it, but didn't see it.

**Review by charleskawczynski — APPROVED** [review]

**Comment by trontrytel** [comment]
bors try

**Review by ilopezgp — APPROVED** [review]
LGTM after rebasing

**Comment by ilopezgp** [comment]
bors try

**Review by charleskawczynski — APPROVED** [review]

**Pull request merged**
