### PR TITLE
Update to TC v0.34, all CliMA deps.

### PR DESCRIPTION
**Pull request by ilopezgp**
## Changes

- Updates the TC engine to version 0.34, effectively going back to the `main` branch of that package;
- Updates to the revamped version of ClimaParameters: v0.4 -> v0.6;
- Updates to the updated CloudMicrophysics: v0.5 -> v0.7;
- Updates SurfaceFluxes and Thermodynamics.
- Adds an integration test of deep convection on a stretched grid, calibrating two microphysics parameters.

## Checklist before requesting a review / merging
- [x] I have formatted the code using `julia --project=.dev .dev/climaformat.jl .`
- [x] I have updated all test manifests using `julia --project .dev/up_deps.jl .` with Julia 1.7.3.
- [x] If core features are added, I have added appropriate test coverage.
- [x] If new functions and structs are added, they are documented through docstrings.

### CODE REVIEW

**Comment by trontrytel** [comment]
Just a heads up - right now all of the microphysics parameters will not be calibrated. They are specified in the generate_namelist file, but that information is not read-in anywhere in TC.jl. It used to be read-in in the `driver/parameter_set.jl` but got deleted

**Comment by ilopezgp** [comment]
> Just a heads up - right now all of the microphysics parameters will not be calibrated. They are specified in the generate_namelist file, but that information is not read-in anywhere in TC.jl. It used to be read-in in the `driver/parameter_set.jl` but got deleted

Can we get an example of this behavior? Then I think we can easily fix this issue with an update_TOML file.

**Comment by trontrytel** [comment]
I was hoping to fix that today, yes. I should have something working for when we meet at 1pm.

Taking `E_liq_rai` parameter as example, I think what is missing is to add to the current `driver/parameter_set.jl`

```
E_liq_rai = TC.parse_namelist(namelist, "microphysics", "E_liq_rai"; default = 0.8)
 
open(override_file, "w") do io                                              
        println(io, "[cloud_liquid_rain_collision_efficiency]")                 
        println(io, "alias = \"E_liq_rai\"")                                    
        println(io, "value = " * string(E_liq_rai))                             
        println(io, "type = \"float\"")   
end
```
Not sure yet what to do if we also want to overwrite those parameter values from the command line

**Comment by ilopezgp** [comment]
> I was hoping to fix that today, yes. I should have something working for when we meet at 1pm.
> 
> Taking `E_liq_rai` parameter as example, I think what is missing is to add to the current `driver/parameter_set.jl`
> 
> ```
> E_liq_rai = TC.parse_namelist(namelist, "microphysics", "E_liq_rai"; default = 0.8)
>  
> open(override_file, "w") do io                                              
>         println(io, "[cloud_liquid_rain_collision_efficiency]")                 
>         println(io, "alias = \"E_liq_rai\"")                                    
>         println(io, "value = " * string(E_liq_rai))                             
>         println(io, "type = \"float\"")   
> end
> ```
> 
> Not sure yet what to do if we also want to overwrite those parameter values from the command line

We can probably deal with the fix from namelist first, since that is what is used by CEDMF. Can you open a draft PR with the changes to TC?

**Comment by trontrytel** [comment]
> We can probably deal with the fix from namelist first, since that is what is used by CEDMF. Can you open a draft PR with the changes to TC?

Yes. Should be done soon.

**Comment by trontrytel** [comment]
> > We can probably deal with the fix from namelist first, since that is what is used by CEDMF. Can you open a draft PR with the changes to TC?
> 
> Yes. Should be done soon.

Maybe not the PR we want, but the PR we need right now: https://github.com/CliMA/TurbulenceConvection.jl/pull/1250

**Comment by trontrytel** [comment]
The tests run for me after I updated everything to this branch. I have submitted a calibration job right now. So hopefully tomorrow I will be able to say if it converged as expected.

**Comment by costachris** [comment]
A NN calibration with this branch seems to be working as expected for me, at least in the first ~25 iterations. Otherwise changes look good to me.

**Comment by trontrytel** [comment]
A TC+CM calibration is working for me. The parameters converge, the resulting simulation is a little different from my previous results. But I think I can work with it. We should update

**Review by trontrytel — APPROVED** [review]

**Comment by ilopezgp** [comment]
I compared this PR to CEDMF v0.7 on SCT1 and SCT2 using Unscented Kalman Inversion. Results are very similar,

Screen Shot 2022-07-27 at 9 40 00 AM

I think we can declare this a success!

**Pull request merged**
