### PR TITLE
Qualify ModelTypes

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR removes the `ModelTypes` module exports and qualifies the model types.

### CODE REVIEW

**Comment by ilopezgp** [comment]
What is the benefit of this change?

**Comment by charleskawczynski** [comment]
> What is the benefit of this change?

It helps users know where to find things (and helps avoid polluting the namespace). We could add an alias if you'd like. It's pretty ubiquitous to qualify things in the python world (`import numpy as np` rather than `import numpy *`)

**Comment by ilopezgp** [comment]
> > What is the benefit of this change?
> 
> It helps users know where to find things (and helps avoid polluting the namespace). We could add an alias if you'd like. It's pretty ubiquitous to qualify things in the python world (`import numpy as np` rather than `import numpy *`)

sounds good! Can we use `ModelTypes...` if we `import CalibrateEDMF.ModelTypes` ? shouldn't this require setting `ModelTypes = CalibrateEDMF.ModelTypes`?

**Comment by charleskawczynski** [comment]
> sounds good! Can we use `ModelTypes...` if we `import CalibrateEDMF.ModelTypes` ? shouldn't this require setting `ModelTypes = CalibrateEDMF.ModelTypes`?

Yep, `import CalibrateEDMF.ModelTypes` brings `ModelTypes` into scope, but nothing else.

**Pull request closed without merging**
