### PR TITLE
ensure adapt_dt is set to TC default after running reference sim

### PR DESCRIPTION
**Pull request by costachris**
Ensure `adapt_dt` is set to TC default after running reference sim.

### CODE REVIEW

**Comment by ilopezgp** [comment]
Good catch! Actually, can you implement a unit test checking the created namelist for some of these things?

**Comment by costachris** [comment]
@ilopezgp I also noticed `get_profile` was occasionally penalizing simulations that finished because of the logic for `dt`, I think this should handle that now?

**Comment by ilopezgp** [comment]
> @ilopezgp I also noticed `get_profile` was occasionally penalizing simulations that finished because of the logic for `dt`, I think this should handle that now.
> 
> ie. previously I was getting:
> 
> ```
> ┌ Warning: Note: Δtstart > dt, which means that simulation stopped before
> │ reaching the requested tstart.Requested t_start = 10800.0 s. However, the
> │ last time available is 21600.0 s.Defaulting to penalized profiles...
> ```

I see. I like your solution but we should have some margin. Can you use `t[end] < tf - dt` in the condition instead?

**Comment by costachris** [comment]
@ilopezgp  I added tests for the changes. `dt` in the SCM output can vary a little (even when `io_frequency` is fixed). I handled this by taking mean(time differences) as `dt` in `get_profile` and use that as the margin for `tf` (with no margin for `ti`)

**Review by ilopezgp — APPROVED** [review]
Thank you! You can bors r+ after rebasing.

**Pull request merged**
