### PR TITLE
Modify simple tutorial, add files to experiment

### PR DESCRIPTION
**Pull request by ilopezgp**

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Maybe we should remove the test in the integration test?

**Comment by ilopezgp** [comment]
It's so bizarre, my local run always converges faster than this

```
mse_full_mean = 380.181675896745, 130.592140385389, 131.212209291145, 
      131.971992889364, _ ;

   mse_full_nn_mean = 374.045763729397, 129.931699454792, 130.570952269217, 
      131.533489068221, _ ;
```

**Comment by ilopezgp** [comment]
I am going to move the prior mean a bit more.

**Pull request merged**
