### PR TITLE
Update to Julia 1.7, TC.jl 0.8

### PR DESCRIPTION
**Pull request by ilopezgp**

### CODE REVIEW

**Comment by ilopezgp** [comment]
Not sure why this is erroring on Windows. The error is

`OpenBLAS: malloc failed in dsyrk_thread_UN
508
ERROR: Package CalibrateEDMF errored during testing`

**Comment by jakebolewski** [comment]
As looks like an OpenBlas threading bug, as a workaround try setting the number of openblas threads to 1 with an ENV variable in CI;

https://github.com/CliMA/ClimaCore.jl/blob/main/.buildkite/pipeline.yml#L4

**Comment by ilopezgp** [comment]
That worked, thanks @jakebolewski !!

**Pull request merged**
