### PR TITLE
Update to Julia 1.8.2

### PR DESCRIPTION
**Pull request by costachris**
## Changes
Update to Julia 1.8.2

## Checklist before requesting a review / merging
- [x] I have formatted the code using `julia --project=.dev .dev/climaformat.jl .`
- [x] I have updated all test manifests using `julia --project .dev/up_deps.jl .` with Julia 1.8.1.
- [x] If core features are added, I have added appropriate test coverage.
- [x] If new functions and structs are added, they are documented through docstrings.

### CODE REVIEW

**Comment by ilopezgp** [comment]
Could you update the pull_request_template as well?

**Comment by costachris** [comment]
@ilopezgp It's updated in this PR. Maybe it's applied to PRs after it's merged? or is there something I need to do on the GitHub site?

**Comment by ilopezgp** [comment]
> @ilopezgp It's updated in this PR. Maybe it's applied to PRs after it's merged?

Oh I didn't see it. Yes, probably

**Review by ilopezgp — APPROVED** [review]

**Comment by ilopezgp** [comment]
Allocations don't seem to have changed much, unfortunately :(

**Pull request merged**
