### PR TITLE
update deps for TCv0.34.3

### PR DESCRIPTION
**Pull request by trontrytel**
## Changes

I want to update to TurbulenceConvection.jl from `v0.34.1` to `v0.34.3` so I ran the `up_deps` script

## Checklist before requesting a review / merging
- [ ] I have formatted the code using `julia --project=.dev .dev/climaformat.jl .`
- [x] I have updated all test manifests using `julia --project .dev/up_deps.jl .` with Julia 1.7.3.
- [ ] If core features are added, I have added appropriate test coverage.
- [ ] If new functions and structs are added, they are documented through docstrings.

### CODE REVIEW

**Comment by trontrytel** [comment]
I'm getting 

```
Internal error: encountered unexpected error in runtime:
OutOfMemoryError()
```

in the Windows CI. Not sure if anything can be done about it @ilopezgp ?

**Comment by ilopezgp** [comment]
The Windows CI is hopeless, let's merge.

**Review by ilopezgp — APPROVED** [review]

**Pull request merged**
