### PR TITLE
Add CNRM-CM5 cases, add SCT3 benchmark

### LINKED ISSUE #436: Fetch LES library dictionaries from TC.jl
We currently have duplicated code in CEDMF and TC regarding the allowable LES_driven_SCM cases. We should just import the dictionaries here from TC.

### PR DESCRIPTION
**Pull request by ilopezgp**
## Changes

- Adds the CNRM-CM5 cases to the allowable TC cases through TC functions, unifies LES libraries with TC codebase.
- Adds a new benchmark, SCT3, with 135 training sites from the AMIP archive (HadGEM2-A + CNRM-CM5), and 15 AMIP4K validation sites from the HadGEM2-A model.
- The SCT3 benchmark should at least contain a config file to calibrate exclusively the data-driven entrainment closure, used as an additive term to the MD closure.
- No regularization used.
- Localization used.
- All physical parameters trained a priori and set to the trained values as defaults through `namelist_args`.

## Issue number (if applicable)

Closes #436 

## Checklist before requesting a review / merging
- [ ] I have formatted the code using `julia --project=.dev .dev/climaformat.jl .`
- [ ] I have updated all test manifests using `julia --project .dev/up_deps.jl .` with Julia 1.7.3.
- [ ] If core features are added, I have added appropriate test coverage.
- [ ] If new functions and structs are added, they are documented through docstrings.

### CODE REVIEW

**Comment by ilopezgp** [comment]
bors try

**Comment by costachris** [comment]
bors try

**Comment by costachris** [comment]
bors try

**Comment by costachris** [comment]
bors try

**Comment by ilopezgp** [comment]
bors try

**Comment by ilopezgp** [comment]
bors try

**Pull request merged**
