### PR TITLE
Set SLURM_CPUS_PER_TASK = 1

### PR DESCRIPTION
**Pull request by charleskawczynski**
@jakebolewski suggested that this may be needed to fix some of the issues we're seeing. One place it showed up was when we incorrectly specified the number of tasks, another place is in the many-node run.

For example, in #211 (and some other CI build in main), we're seeing
```
Worker 10 terminated.
  | Unhandled Task ERROR: EOFError: read end of file
  | Stacktrace:
  | [1] (::Base.var"#wait_locked#645")(s::Sockets.TCPSocket, buf::IOBuffer, nb::Int64)
...

Worker 9 terminated.
  | Unhandled Task ERROR: IOError: read: connection reset by peer (ECONNRESET)
  | Stacktrace:
  | [1] wait_readnb(x::Sockets.TCPSocket, nb::Int64)
  | @ Base ./stream.jl:408
  | [2] (::Base.var"#wait_locked#645")(s::Sockets.TCPSocket, buf::IOBuffer, nb::Int64)
 ```

### CODE REVIEW

**Comment by charleskawczynski** [comment]
CI passed on this run, let's see if it makes things more stable.

**Comment by ilopezgp** [comment]
Do you think this will affect compilation time @charleskawczynski ?

**Comment by charleskawczynski** [comment]
> Do you think this will affect the number of times we compile @charleskawczynski ?

No, I don't think so, the first push I ran finished in 16 min.

**Comment by jakebolewski** [comment]
you can do this with `slurm_cpus_per_task: 1` in the config

**Comment by jakebolewski** [comment]
I think I also suggested setting the number of tasks to 1 and the number of cpus per task to N given the job which would allocate them on a single node

**Comment by charleskawczynski** [comment]
> can do this with `slurm_cpus_per_task: 1` (to pass as the cli option) in the build kite config

Is what I've done in this PR equivalent?

**Comment by charleskawczynski** [comment]
Ref: https://www.hpc.caltech.edu/documentation/slurm-commands

**Pull request merged**
