### PR TITLE
update results folder naming convention

### PR DESCRIPTION
**Pull request by haakon-e**
PR intends to make output folders more easily differentiable by appending the current DateTime instead of a random number.

### CODE REVIEW

**Comment by jakebolewski** [comment]
I'm not sure if you are doing distributed training yet (multiple nodes writing output), but it is good to order by datetime + some random alpha/numeric postfix to break ties due to possible clock skew (so you don't have conflicts, or you make them extremely rare).

**Comment by ilopezgp** [comment]
I agree with @jakebolewski . The random number helps when you are launching jobs almost simultaneously. In that case, the date is not too informative. I like the idea of adding the date if that is useful. Maybe yr-mm-dd + random number is a good balance?

**Comment by haakon-e** [comment]
What do you think about this option, @jakebolewski @ilopezgp?
length 3 alphanumeric string is ~260k combinations, up from ~80k combinations with the existing generator.

**Comment by ilopezgp** [comment]
I like the random string. Do we want to save the minutes in the date, though?

**Comment by haakon-e** [comment]
I think minutes can be useful for people who are testing the pipeline or run smaller calibrations to differentiate successive runs in a shorter timeframe.

**Review by ilopezgp — APPROVED** [review]
Sounds good. Let's keep minutes then.

**Pull request merged**
